@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("adm", $fontColor="#d73027")

Person(personAlias, "Usúario", "Responsável por fazer a encomenda")
System(mobile, "Menu Lancheirinha", "Aplicativo de encomenda de lancheiras saudáveis")

Person(Admin, "Admin", "Responsável por gerenciar os pedidos", $tags="adm")

System(whatsapp, "WhatsApp da Empresa", "Canal de comunicação para receber informações de vendas")

Rel(mobile, whatsapp, "Pedido de lancheirinhas")
Rel(whatsapp, Admin, "Comunicação de vendas")

Rel(personAlias, mobile, "Fazer pedido")
Rel(Admin, mobile, "Liberar pedidos")
@enduml

// Adicione uma linha em branco ou um comentário para separar os diagramas

@startuml C4_Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("adm", $fontColor="#d73027")

Person(user, "Usuário", "Cliente que usa o aplicativo para comprar lancheirinhas")
System(app, "Aplicativo Flutter", "Aplicativo de venda de lancheirinhas saudáveis em Flutter")
Container(auth, "Autenticação", "Firebase Authentication", "Gerencia a autenticação de usuários")
Container(db, "Banco de Dados", "Firebase Firestore", "Armazena informações sobre clientes, pedidos e lancheirinhas")
Container(payment, "Pagamentos", "Gateway de pagamento", "Processa os pagamentos dos pedidos")
Container(notif, "Notificações", "Firebase Cloud Messaging", "Envia notificações aos usuários")
System(whatsapp, "WhatsApp da Empresa", "Canal de comunicação para receber informações de vendas")

Person(Admin, "Admin", "Responsável por gerenciar os pedidos", $tags="adm")

Rel(user, app, "Acessa")
Rel(app, auth, "Autentica usuário")
Rel(app, db, "Armazenamento dados")
Rel(app, payment, "Processo pagamentos")
Rel(app, notif, "Envia notificações")
Rel(notif, whatsapp, "Envia informações de vendas")
Rel_R(Admin, whatsapp, "Realiza Negociações")

@enduml

@startuml C4_Components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System(app, "Aplicativo Flutter", "Aplicativo de venda de lancheirinhas saudáveis em Flutter")
Component(authComp, "Firebase Authentication", "Gerencia a autenticação de usuários")

System(app, "Aplicativo Flutter", "Aplicativo de venda de lancheirinhas saudáveis em Flutter")
Component(dbComp, "Firebase Firestore", "Armazena informações sobre clientes, pedidos e lancheirinhas")

System(app, "Aplicativo Flutter", "Aplicativo de venda de lancheirinhas saudáveis em Flutter")
Component(paymentComp, "Gateway de Pagamento", "Processa os pagamentos dos pedidos")
System(whatsapp, "WhatsApp da Empresa", "Canal de comunicação para receber informações de vendas")

Rel(app, paymentComp, "Utiliza Gateway de Pagamento para processar pagamentos")
Rel(paymentComp, whatsapp, "Envia informações de vendas para WhatsApp da Empresa")

Rel(app, dbComp, "Utiliza Firebase Firestore para armazenamento de dados")

Rel(app, authComp, "Utiliza Firebase Authentication para autenticação")
@enduml

@startuml
class LoginPage {
    - FormularioDeLogin formulario
    - ServicoDeAutenticacao servicoAutenticacao
    + void exibirPagina()
}

class FormularioDeLogin {
    - String usuario
    - String senha
    + void validarCampos()
}

class ServicoDeAutenticacao {
    + boolean autenticar(String usuario, String senha)
}

LoginPage --> FormularioDeLogin: contém
LoginPage --> ServicoDeAutenticacao: utiliza
FormularioDeLogin --> ServicoDeAutenticacao: utiliza
@enduml






